# Credential Attributes Mapping - PID (Personal Identification Data)
#
# This file defines the mapping between a common attribute name used in the
# credential template (e.g. graphic/display rendering) and its
# corresponding representation in different credential formats (sd-jwt-vc, mdoc-cbor).
# It allows the system to translate the same credential attribute across formats.
#
# Supported configuration fields for each attribute entry:
#
#   <attribute_name>:           Top-level key representing the attribute name as used in the credential jinja2 template.
#                               It can be a dot-separated path which will be translated into a nested object structure.
#     <format>:                Credential format.
#       namespace: (optional)  The namespace used in mdoc-cbor to group attributes.
#       subgroup: (optional)   A logical subgroup within the credential.
#       element_identifier:    The actual attribute name as used in the specific format.
#                              This is the key that will appear in the issued credential.

metadata.iat:
  sd-jwt-vc:
    subgroup: "verification"
    element_identifier: "iat"
  mdoc-cbor:
    subgroup: "validityInfo"
    element_identifier: "validFrom"
metadata.exp:
  sd-jwt-vc:
    element_identifier: "exp"
  mdoc-cbor:
    subgroup: "validityInfo"
    element_identifier: "validUntil"
metadata.nbf:
  sd-jwt-vc:
    element_identifier: "nbf"
  mdoc-cbor:
    subgroup: "validityInfo"
    element_identifier: "signed"

given_name:
  sd-jwt-vc:
    element_identifier: "given_name"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.1"
    element_identifier: "given_name"

family_name:
  sd-jwt-vc:
    element_identifier: "family_name"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.1"
    element_identifier: "family_name"

birthdate:
  sd-jwt-vc:
    element_identifier: "birthdate"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.1"
    element_identifier: "birth_date"

place_of_birth:
  sd-jwt-vc:
    element_identifier: "place_of_birth"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.1"
    element_identifier: "place_of_birth"

tax_id_code:
  sd-jwt-vc:
    element_identifier: "tax_id_code"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.it.1"
    element_identifier: "tax_id_code"

nationalities:
  sd-jwt-vc:
    element_identifier: "nationalities"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.1"
    element_identifier: "nationality"

tax_id_code:
  sd-jwt-vc:
    element_identifier: "tax_id_code"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.it.1"
    element_identifier: "tax_id_code"

sub:
  sd-jwt-vc:
    element_identifier: "sub"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.1"
    element_identifier: "sub"

trust_framework:
  sd-jwt-vc:
    subgroup: "verification"
    element_identifier: "trust_framework"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.1"
    subgroup: "verification"
    element_identifier: "trust_framework"
assurance_level:
  sd-jwt-vc:
    subgroup: "verification"
    element_identifier: "assurance_level"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.1"
    subgroup: "verification"
    element_identifier: "assurance_level"

issuing_country:
  sd-jwt-vc:
    element_identifier: "issuing_country"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.1"
    element_identifier: "issuing_country"

issuing_authority:
  sd-jwt-vc:
    element_identifier: "issuing_authority"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.1"
    element_identifier: "issuing_authority"

date_of_expiry:
  sd-jwt-vc:
    element_identifier: "date_of_expiry"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.1"
    element_identifier: "expiry_date"

issuance_date:
  sd-jwt-vc:
    element_identifier: "issuance_date"
  mdoc-cbor:
    namespace: "eu.europa.ec.eudi.pid.1"
    element_identifier: "issuance_date"
