services:

  wallet-instance:
    image: iam-proxy-italia-wallet-istance-demo:1.3.3
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iam-proxy-italia-wallet-istance-demo
    environment:
      - FLASK_RUN_PORT=8080
      - PYTHONUNBUFFERED=1
      - CONFIG_DIR=/application/config
      - POETRY_VERSION=2.3.2
      - TZ=Europe/Rome
    ports:
      - "8080:8080"
    volumes:
      - ./config:/application/config:rwxo
    restart: unless-stopped
    networks:
      - iam-proxy-italia

networks:
  iam-proxy-italia:
    external: true