[project]
name = "iam-proxy-italia-wallet-instance-demo"
readme = "README.md"
requires-python = ">=3.10"

[tool.ruff]
target-version = "py310"
line-length = 120
exclude = [".ci_env", ".ci-venv", ".git", "__pycache__", ".venv", "venv", "static", "templates"]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501", "F401"]

[tool.ruff.format]
quote-style = "double"

[tool.radon]
min = "B"

[tool.xenon]
max_absolute = "B"
max_modules = "B"
max_average = "A"
