supported_credentials:
  dc_sd_jwt_pid:
    proto_version: "1.3.3" #currently unused, for future releases
    valid_for_wallet_activation: true #currently unused, for future releases
    internal_mapping_ref: "pid"
    document_identifier:
      type: "vct"
      value: "urn:it-wallet:pid:1"
    document_format:
      id: "sd-jwt-vc"
      specs:

  mso_mdoc_pid:
    proto_version: "1.3.3" #currently unused, for future releases
    valid_for_wallet_activation: true #currently unused, for future releases
    internal_mapping_ref: "pid"
    document_identifier:
      type: "doctype"
      value: "eu.europa.ec.eudi.pid.1"
    document_format:
      id: "mdoc-cbor"
      specs:
        "namespaces": [
          "eu.europa.ec.eudi.pid.1",
          "eu.europa.ec.eudi.pid.it.1"
        ]
        "version": "1.0"

  mso_mdoc_mDL:
    proto_version: "1.3.3" #currently unused, for future releases
    valid_for_wallet_activation: false #currently unused, for future releases
    internal_mapping_ref: "mDL"
    document_identifier:
      type: "doctype"
      value: "org.iso.18013.5.1"
    document_format:
      id: "mdoc-cbor"
      specs:
        "namespaces": [
          "org.iso.18013.5.1.mDL",
          "org.iso.18013.5.1.mDL.it"
        ]
        "version": "1.0"

internal_attributes_mappings:
    pid: !INCLUDE credentials/pid.yaml